# Generated by Django 6.0.7 on 2026-07-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="e.g. hero, about, timeline, tech-stack, projects, pricing, blog, contact",
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable name shown in the dashboard",
                        max_length=100,
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
