# Generated by Django 6.0.7 on 2026-07-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0002_sitesection"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="Short punchy line shown as the big About headline, e.g. 'I build backend systems that scale.'",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="summary",
            field=models.TextField(
                help_text="Full bio paragraph, shown as regular body text under the tagline."
            ),
        ),
    ]
