# Generated by Django 6.0.7 on 2026-07-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0003_profile_tagline_alter_profile_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preset",
                    models.CharField(
                        choices=[
                            ("custom", "Custom"),
                            ("lime-ink", "Lime & Ink"),
                            ("ocean-blue", "Ocean Blue"),
                            ("sunset-orange", "Sunset Orange"),
                            ("violet-dusk", "Violet Dusk"),
                            ("forest-green", "Forest Green"),
                            ("crimson-rose", "Crimson Rose"),
                        ],
                        default="lime-ink",
                        max_length=30,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#d9ff4b",
                        help_text="Hex color, e.g. #d9ff4b",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#0a0a0a",
                        help_text="Hex color, e.g. #0a0a0a",
                        max_length=7,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site theme",
            },
        ),
    ]
