# Generated by Django 6.0.7 on 2026-07-21 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0004_sitetheme"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                (
                    "body_html",
                    models.TextField(
                        help_text="Rich text HTML body, before branded email wrapping."
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "send_error",
                    models.CharField(
                        blank=True, help_text="Set if SMTP send failed.", max_length=500
                    ),
                ),
                (
                    "contact_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Left blank for standalone Compose emails not tied to an inbound message.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="portfolio_api.contactmessage",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
