# Generated by Django 6.0.7 on 2026-07-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0005_emailreply"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whatsapp_enabled", models.BooleanField(default=True)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        default="+9779843951313",
                        help_text="Include country code, e.g. +9779843951313 (no spaces or dashes).",
                        max_length=20,
                    ),
                ),
                (
                    "whatsapp_default_message",
                    models.CharField(
                        blank=True,
                        default="Hi! I saw your portfolio and would like to get in touch.",
                        help_text="Prefilled message when a visitor opens the WhatsApp chat.",
                        max_length=300,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site widgets",
            },
        ),
    ]
