# Generated by Django 6.0.7 on 2026-07-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0006_sitewidget"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitewidget",
            name="blog_share_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitewidget",
            name="cookie_banner_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitewidget",
            name="cookie_banner_message",
            field=models.CharField(
                blank=True,
                default="This site collects basic, anonymous visit analytics (page views, device type) to help improve the experience. No personal data is sold or shared.",
                help_text="Text shown in the dismissible cookie/analytics consent banner.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="sitewidget",
            name="resume_download_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitewidget",
            name="scroll_to_top_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="sitetheme",
            name="preset",
            field=models.CharField(
                choices=[
                    ("custom", "Custom"),
                    ("lime-ink", "Lime & Ink"),
                    ("ocean-blue", "Ocean Blue"),
                    ("sunset-orange", "Sunset Orange"),
                    ("violet-dusk", "Violet Dusk"),
                    ("forest-green", "Forest Green"),
                    ("crimson-rose", "Crimson Rose"),
                    ("rose-gold", "Rose Gold"),
                    ("slate-blue", "Slate Blue"),
                    ("amber-noir", "Amber Noir"),
                    ("mint-fresh", "Mint Fresh"),
                    ("deep-plum", "Deep Plum"),
                    ("coral-reef", "Coral Reef"),
                    ("cyber-teal", "Cyber Teal"),
                    ("golden-hour", "Golden Hour"),
                    ("electric-indigo", "Electric Indigo"),
                    ("monochrome", "Monochrome"),
                    ("cherry-blossom", "Cherry Blossom"),
                    ("arctic-frost", "Arctic Frost"),
                    ("volcanic-red", "Volcanic Red"),
                    ("neon-cyber", "Neon Cyber"),
                ],
                default="lime-ink",
                max_length=30,
            ),
        ),
    ]
