# Generated by Django 6.0.7 on 2026-07-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0007_sitewidget_blog_share_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="certificate_file",
            field=models.FileField(
                blank=True,
                help_text="Optional certificate image or PDF. If uploaded, shown on the public site with a preview.",
                null=True,
                upload_to="certificates/",
            ),
        ),
    ]
