# Generated by Django 6.0.7 on 2026-07-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0008_training_certificate_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter / X"),
                            ("youtube", "YouTube"),
                            ("telegram", "Telegram"),
                            ("discord", "Discord"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("is_visible", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.RemoveField(
            model_name="profile",
            name="facebook_url",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="github_url",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="linkedin_url",
        ),
        migrations.AlterField(
            model_name="profile",
            name="portfolio_url",
            field=models.URLField(
                blank=True,
                help_text="Link to a separate personal site/blog, if any — not a social platform.",
            ),
        ),
    ]
