# Generated by Django 6.0.7 on 2026-07-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0009_sociallink_remove_profile_facebook_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notify_owner_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Send an email to CONTACT_RECEIVER_EMAIL (from settings/.env) whenever the contact form is submitted.",
                    ),
                ),
                (
                    "auto_reply_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Send a confirmation email back to the visitor who submitted the contact form.",
                    ),
                ),
                (
                    "auto_reply_subject",
                    models.CharField(
                        blank=True,
                        default="Thanks for reaching out!",
                        help_text="Subject line of the auto-reply sent to the visitor.",
                        max_length=200,
                    ),
                ),
                (
                    "auto_reply_message",
                    models.TextField(
                        blank=True,
                        default="Hi {name},\n\nThanks for getting in touch! I've received your message and will get back to you as soon as I can.\n\nBest,\n{owner_name}",
                        help_text="Body of the auto-reply. {name} and {owner_name} are replaced with the visitor's name and the site owner's name.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email settings",
            },
        ),
    ]
