# Generated by Django 6.0.7 on 2026-07-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0010_emailsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Optional callback number the visitor left.",
                max_length=30,
            ),
        ),
    ]
